apiVersion: v1
kind: ConfigMap
metadata:
  name: quote-app-cm
data:
  DATABASE_URL: "127.0.0.1"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "my-app-db"
  DATABASE_USER: "my-gsa@guptaji-tech-public.iam"
  DATABASE_MODE: "disable"